//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProfilicEmlakEntities1 : DbContext
    {
        public ProfilicEmlakEntities1()
            : base("name=ProfilicEmlakEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_admin> TBL_admin { get; set; }
        public virtual DbSet<TBL_aylık_gelir> TBL_aylık_gelir { get; set; }
        public virtual DbSet<TBL_evsahibi> TBL_evsahibi { get; set; }
        public virtual DbSet<TBL_gayrimenkul_durum> TBL_gayrimenkul_durum { get; set; }
        public virtual DbSet<TBL_kasa> TBL_kasa { get; set; }
        public virtual DbSet<TBL_kiraci> TBL_kiraci { get; set; }
        public virtual DbSet<TBL_konut> TBL_konut { get; set; }
        public virtual DbSet<TBL_konutturu> TBL_konutturu { get; set; }
        public virtual DbSet<TBL_sozlesme> TBL_sozlesme { get; set; }
    }
}
