//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_konutturu
    {
        public int tur_id { get; set; }
        public string konuttur_ad { get; set; }
        public Nullable<int> oda_sayısı { get; set; }
        public Nullable<int> metre_kare { get; set; }
        public string adres { get; set; }
        public string ısınma_turu { get; set; }
        public string esyalimi { get; set; }
        public string gayrimenkul_durum { get; set; }
    }
}
