//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_kiraci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_kiraci()
        {
            this.TBL_konut = new HashSet<TBL_konut>();
            this.TBL_sozlesme = new HashSet<TBL_sozlesme>();
        }
    
        public int kiraci_id { get; set; }
        public string kiraci_tc { get; set; }
        public string kiraci_ad { get; set; }
        public string kiraci_soyad { get; set; }
        public string apartman_blok { get; set; }
        public Nullable<int> kiraci_daire_no { get; set; }
        public Nullable<int> kira_gun { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_konut> TBL_konut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_sozlesme> TBL_sozlesme { get; set; }
    }
}
