//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_sozlesme
    {
        public int soz_id { get; set; }
        public Nullable<int> konut_id { get; set; }
        public Nullable<int> kiraci_id { get; set; }
        public Nullable<int> konutsahibi_id { get; set; }
        public Nullable<System.DateTime> soz_tarih { get; set; }
        public string kontrat_bilgisi { get; set; }
        public Nullable<int> depozito_tutar { get; set; }
        public Nullable<bool> depozito_durum { get; set; }
    
        public virtual TBL_evsahibi TBL_evsahibi { get; set; }
        public virtual TBL_kiraci TBL_kiraci { get; set; }
        public virtual TBL_konut TBL_konut { get; set; }
    }
}
