//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_evsahibi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_evsahibi()
        {
            this.TBL_aylık_gelir = new HashSet<TBL_aylık_gelir>();
            this.TBL_kasa = new HashSet<TBL_kasa>();
            this.TBL_konut = new HashSet<TBL_konut>();
            this.TBL_sozlesme = new HashSet<TBL_sozlesme>();
        }
    
        public int konuts_id { get; set; }
        public string konuts_tc { get; set; }
        public string konuts_ad { get; set; }
        public string konuts_soyad { get; set; }
        public Nullable<int> konut_sayisi { get; set; }
        public string konuts_iban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_aylık_gelir> TBL_aylık_gelir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_kasa> TBL_kasa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_konut> TBL_konut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_sozlesme> TBL_sozlesme { get; set; }
    }
}
