//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_gayrimenkul_durum
    {
        public int gayrimenkul_durum_id { get; set; }
        public Nullable<int> tur_id { get; set; }
        public string gayrimenkul_drm { get; set; }
        public string gayrimenkul_tip { get; set; }
    }
}
