//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_kasa
    {
        public int kasa_id { get; set; }
        public Nullable<int> konut_sahibi_id { get; set; }
        public Nullable<int> gelir { get; set; }
        public Nullable<int> gider { get; set; }
        public Nullable<System.DateTime> ay { get; set; }
        public Nullable<double> net_gelir { get; set; }
    
        public virtual TBL_evsahibi TBL_evsahibi { get; set; }
    }
}
