//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_admin
    {
        public int Admin_id { get; set; }
        public string Admin_ad { get; set; }
        public string Admin_sifre { get; set; }
        public Nullable<bool> Rol { get; set; }
    }
}
