//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_aylık_gelir
    {
        public int konut_sahibi { get; set; }
        public Nullable<int> ev_sahibi_id { get; set; }
        public Nullable<decimal> Ocak { get; set; }
        public Nullable<decimal> Subat { get; set; }
        public Nullable<decimal> Mart { get; set; }
        public Nullable<decimal> Nisan { get; set; }
        public Nullable<decimal> Mayis { get; set; }
        public Nullable<decimal> Haziran { get; set; }
        public Nullable<decimal> Temmuz { get; set; }
        public Nullable<decimal> Agustos { get; set; }
        public Nullable<decimal> Eylul { get; set; }
        public Nullable<decimal> Ekim { get; set; }
        public Nullable<decimal> Kasim { get; set; }
        public Nullable<decimal> Aralik { get; set; }
    
        public virtual TBL_evsahibi TBL_evsahibi { get; set; }
    }
}
