//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_konut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_konut()
        {
            this.TBL_sozlesme = new HashSet<TBL_sozlesme>();
        }
    
        public int konut_id { get; set; }
        public Nullable<int> konutsahibi_id { get; set; }
        public Nullable<int> kiraci_id { get; set; }
        public string konut_adres { get; set; }
        public Nullable<int> kira_tutar { get; set; }
        public Nullable<bool> Kira_Durum { get; set; }
    
        public virtual TBL_evsahibi TBL_evsahibi { get; set; }
        public virtual TBL_kiraci TBL_kiraci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_sozlesme> TBL_sozlesme { get; set; }
    }
}
